version: '3.7'

services:
  app: 
    image: app_nest_flights:v1
    container_name: app_nest_flights
    build: .
    env_file: .env
    ports: 
      - 4000:4000
    depends_on:
      - mongodb
    restart: always
    networks:
      - ms_nestjs1

  mongodb: 
    image: mongo:latest
    container_name: mongodb_fl
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes: 
      - mongodb:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - ms_nestjs1

volumes:
  mongodb:

networks:
  ms_nestjs1:

    