version: '3.7'

services:
  app: 
    image: app_nest_bd:v1
    container_name: app_nest_bd
    build: .
    env_file: .env
    ports: 
      - 3001:3001
    depends_on:
      - mongodb
    restart: always
    networks:
      - ms_nestjs

  mongodb: 
    image: mongo:latest
    container_name: mongodb_img
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes: 
      - mongodb:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - ms_nestjs

volumes:
  mongodb:

networks:
  ms_nestjs:

    